# Configuración del servicio externo (PuntoRed/GestoPago)
gestopago.api.url=https://gestopago.portalventas.net
gestopago.api.token=COLOCA_AQUI_TU_BEARER_TOKEN
gestopago.api.key=YSX1HpAFum4TpCecyFBxs4eljAlbhKqK6fpcSQp8

# Configuración del auth (existente en el proyecto por el servicio GestoPagoTokenService)
gestopago.auth.url=https://gestopago.portalventas.net
gestopago.auth.id-distribuidor=83
gestopago.auth.codigo-dispositivo=GPS83-TPV-17
gestopago.auth.password=12345678

# Configuración de Base de Datos (Neon Postgres)
spring.datasource.url=jdbc:postgresql://ep-billowing-sound-b4r1k9ty-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_wd5QWl0cbDOP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Deshabilitar chequeo de Spring Cloud Config Server (no requerido para ejecución local)
spring.cloud.config.enabled=false
